CC := avr-gcc
CFLAGS := -Os -DF_CPU=8000000UL -mmcu=atmega168

USART_LIBRARY_DIR := ./
USART_LIBRARY_NAME := USART
USART_LIBRARY_OBJ_DIR := $(USART_LIBRARY_DIR)src/
USART_LIBRARY_INC_DIR := $(USART_LIBRARY_DIR)inc/
USART_LIBRARY_SRC := $(wildcard $(USART_LIBRARY_OBJ_DIR)*.c)
USART_LIBRARY_OBJ := $(USART_LIBRARY_SRC:.c=.o)
USART_LIBRARY_AR := ar -rcs

# default rule to build .a library
all: $(USART_LIBRARY_NAME).a

$(USART_LIBRARY_NAME).a: $(USART_LIBRARY_OBJ)
	$(USART_LIBRARY_AR) $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -I$(USART_LIBRARY_INC_DIR) -c $< -o $@

clean:
	rm -f $(USART_LIBRARY_NAME).a $(USART_LIBRARY_OBJ)